# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    create_views = (
        '''CREATE OR REPLACE VIEW hello_customer_history_v
              AS SELECT 
                    row_number() OVER () AS id,
                    customer_id,
                    favourite_items."product_id",
                    category AS product_category,
                    price AS product_price,
                    full_name AS product_name,
                    description AS product_description
                  FROM (SELECT DISTINCT hello_sale."customer_id",
                                        hello_order_items."product_id"
                        FROM hello_sale
                        JOIN hello_order_items
                          ON hello_sale."sale_id" = hello_order_items."sale_id"
                        ORDER BY hello_sale."customer_id"
                  ) AS favourite_items
                  JOIN hello_product
                    ON favourite_items."product_id" = hello_product."product_id"
                  ORDER BY customer_id
        ''',
        '''CREATE OR REPLACE VIEW hello_low_stock
              AS SELECT 
                   row_number() OVER () AS id,
                   low_totals.pId AS Product_id,
                   low_totals.qty AS Stock,
                   quantity       AS SupplierStock,
                   name           AS SupplierName,
                   phone_no,
                   email,
                   address
                 FROM (SELECT 
                         product_id    AS pId,
                         SUM(quantity) AS qty
                       FROM hello_stock
                       GROUP BY product_id
                       HAVING SUM(quantity) < 100
                       ) AS low_totals 
                       LEFT JOIN (hello_supplier_stock 
                              JOIN hello_supplier 
                                JOIN hello_supplier_contact
                                  ON hello_supplier."supplier_id" = hello_supplier_contact."supplier_id"
                                    ON hello_supplier."supplier_id" = hello_supplier_stock."supplier_id")
                       ON low_totals.pId = hello_supplier_stock."product_id"
                 ORDER BY low_totals."qty"
        ''',
        '''CREATE OR REPLACE VIEW hello_sales_by_amount
                AS SELECT
                    row_number() OVER () AS id, 
                    hello_sale.*,
                    totals.total_amount
                   FROM (SELECT
                          d.sale_id,
                          SUM(d.quantity * p.price) AS total_amount
                         FROM hello_order_items d
                          JOIN hello_product p
                            ON d.product_id = p."product_id"
                         GROUP BY d.sale_id
                        ) AS totals
                        JOIN hello_sale
                        ON hello_sale."sale_id" = totals.sale_id
                   WHERE NOT hello_sale.order_status = 'RJ'
                   ORDER BY totals.total_amount DESC
        '''
    )

    operations = [
        migrations.RunSQL(command) for command in create_views
    ]
