# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='full_name',
            field=models.CharField(max_length=500),
        ),
    ]
