# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pId', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('full_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('whId', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
