# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20171022_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier_contact',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='supplier_contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(max_length=120),
        ),
    ]
