# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_customer_sale_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
