# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20171022_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
